version: '3.8'

services:
  app:
    build: ./app
    container_name: museumwiki_app
    ports:
      - "5001:5000"  # Changé le port pour éviter conflits
    volumes:
      - ./data:/app/data
    environment:
      - DATA_PATH=/app/data/artworks_latest.csv
